# The URL the site will be built for
base_url = "https://adrs.pub"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "anemone"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
toc = true
display_author = true
footer_content_license = "🄯 2024 adrs all rites reversed"
footer_content_license_link = "/last-copyrites"

header_nav = [
    { url = "/", name_en = "/home/" },
    { url = "/about", name_en = "/about/" },
    { url = "/resume", name_en = "/resume/" },
    { url = "/blog", name_en = "/blog/" },
]
